stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      demands:
      - msbuild
      - visualstudio
      vmImage: 'windows-2022'
    variables:
      solution: '**\src\VSTSDemoGeneratorV2.sln'
      artifactName: 'drop'
    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 5.11.0'
      inputs:
        versionSpec: 5.11.0
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:Configuration=Debug /p:Platform="Any CPU" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    - task: CopyFiles@1
      displayName: 'Copy Files to: $(build.sourcesdirectory)\src\VstsDemoBuilder\obj\Release\Package\PackageTmp'
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)\' 
        Contents: '**\*'
        TargetFolder: '$(build.sourcesdirectory)\Artifacts'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.sourcesdirectory)\Artifacts'
        ArtifactName: '$(artifactName)'

- stage: Staging
  condition: and(succeeded(), or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'PullRequest')))
  dependsOn: Build
  displayName: Staging Deployment
  jobs:   
  - deployment: Staging
    environment: 'Staging'
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzureDevOpsDemoGenProd'
              appType: 'webApp'
              WebAppName: 'azuredevopsdemogenerator'
              deployToSlotOrASE: true
              ResourceGroupName: 'azuredevopsdemogenerator-production-group'
              SlotName: 'staging'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              AppSettings: '-DefaultTemplate eShopOnWeb -Password $(Password) -ClientId $(ClientId-stage) -ClientSecret $(ClientSecret-stage) -RedirectUri $(RedirectUri-stage) -AppScope $(AppScope-stage)'
              enableCustomDeployment: true
              DeploymentType: 'webDeploy'

- stage: Preprod
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  dependsOn: Build
  displayName: Preprod Deployment
  jobs:   
  - deployment: Preprod
    environment: 'Preprod'
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzureDevOpsDemoGenProd'
              appType: 'webApp'
              WebAppName: 'azuredevopsdemogenerator'
              deployToSlotOrASE: true
              ResourceGroupName: 'azuredevopsdemogenerator-production-group'
              SlotName: 'preprod'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              AppSettings: '-DefaultTemplate eShopOnWeb -Password $(Password) -ClientId $(ClientId-preprod) -ClientSecret $(ClientSecret-preprod) -RedirectUri $(RedirectUri-preprod) -AppScope $(AppScope-preprod)'
              enableCustomDeployment: true
              DeploymentType: 'webDeploy'

- stage: Prod
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  dependsOn: Preprod
  displayName: Prod Deployment
  jobs:   
  - deployment: Prod
    environment: 'Prod'
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            displayName: App Service Manage
            inputs:
              azureSubscription: 'AzureDevOpsDemoGenProd'
              Action: 'Swap Slots'
              WebAppName: 'azuredevopsdemogenerator'
              ResourceGroupName: 'azuredevopsdemogenerator-production-group'
              SourceSlot: 'preprod'