using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VstsDemoBuilder.Models
{
    public class Value
    {
        public string value { get; set; }
        public DateTime timeStamp { get; set; }
        public string size { get; set; }
        public bool isAutoGenerated { get; set; }
    }
    public class Avatar
    {
        public Value value { get; set; }
    }
    public class CoreAttributes
    {
        public Avatar Avatar { get; set; }
    }
    public class ProfileDetails
    {
        public CoreAttributes coreAttributes { get; set; }
        public string displayName { get; set; }
        public string publicAlias { get; set; }
        public string emailAddress { get; set; }
        public string id { get; set; }
        public string ErrorMessage { get; set; }
    }
}