var searchData=
[
  ['iconfiguration',['IConfiguration',['../interface_vsts_demo_builder_1_1_models_1_1_i_configuration.html',1,'VstsDemoBuilder.Models.IConfiguration'],['../interface_vsts_rest_a_p_i_1_1_i_configuration.html',1,'VstsRestAPI.IConfiguration'],['../interface_templates_generator_tool_1_1_i_configuration.html',1,'TemplatesGeneratorTool.IConfiguration']]],
  ['importworkitemmodel',['ImportWorkItemModel',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_import_work_item_model.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['importworkitems',['ImportWorkItems',['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_import_work_items.html',1,'VstsRestAPI.WorkItemAndTracking.ImportWorkItems'],['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_import_work_items.html#a314f15de4c9b09b3911af9d079abe306',1,'VstsRestAPI.WorkItemAndTracking.ImportWorkItems.ImportWorkitems()']]],
  ['index',['Index',['../class_vsts_demo_builder_1_1_controllers_1_1_account_controller.html#ac36624619c06ea1c9e9df88c06d9a80f',1,'VstsDemoBuilder::Controllers::AccountController']]],
  ['inputs',['Inputs',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_release_definition_1_1_release_definitions_1_1_inputs.html',1,'VstsRestAPI.Viewmodel.ReleaseDefinition.ReleaseDefinitions.Inputs'],['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_inputs.html',1,'TemplatesGeneratorTool.ViewModel.BuildDefinitions.Inputs'],['../class_templates_generator_tool_1_1_view_model_1_1_release_definitions_1_1_inputs.html',1,'TemplatesGeneratorTool.ViewModel.ReleaseDefinitions.Inputs']]],
  ['inputs1',['Inputs1',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_inputs1.html',1,'TemplatesGeneratorTool::ViewModel::BuildDefinitions']]],
  ['installextensions',['InstallExtensions',['../class_vsts_demo_builder_1_1_controllers_1_1_environment_controller.html#a8c6be4b2363680d958e6fdee4e74b91a',1,'VstsDemoBuilder::Controllers::EnvironmentController']]],
  ['iphostgenerator',['IPHostGenerator',['../class_vsts_demo_builder_1_1_models_1_1_location_1_1_i_p_host_generator.html',1,'VstsDemoBuilder::Models::Location']]],
  ['isaccounthasprojects',['IsAccountHasProjects',['../class_vsts_rest_a_p_i_1_1_projects_and_teams_1_1_projects.html#a5972180d08f6a32c0a22c03f94622904',1,'VstsRestAPI::ProjectsAndTeams::Projects']]],
  ['issuewi',['IssueWI',['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_issue_w_i.html',1,'VstsRestAPI::WorkItemAndTracking']]],
  ['isvalidaccount',['isValidAccount',['../class_templates_generator_tool_1_1_generators_1_1_validate_login.html#ab3bf9583c98282065b77f2a35ddeacd2',1,'TemplatesGeneratorTool::Generators::ValidateLogin']]],
  ['iterationcontext',['IterationContext',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_repository_1_1_pull_request_comments_1_1_iteration_context.html',1,'VstsRestAPI.Viewmodel.Repository.PullRequestComments.IterationContext'],['../class_templates_generator_tool_1_1_view_model_1_1_pull_request_comment_response_1_1_iteration_context.html',1,'TemplatesGeneratorTool.ViewModel.PullRequestCommentResponse.IterationContext']]],
  ['iterations',['Iterations',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_project_and_teams_1_1_team_iterations_response_1_1_iterations.html',1,'VstsRestAPI::Viewmodel::ProjectAndTeams::TeamIterationsResponse']]]
];
