var searchData=
[
  ['widget',['Widget',['../class_templates_generator_tool_1_1_view_model_1_1_widget_and_chart_response_1_1_widget.html',1,'TemplatesGeneratorTool::ViewModel::WidgetAndChartResponse']]],
  ['widgetandchartresponse',['WidgetAndChartResponse',['../class_templates_generator_tool_1_1_view_model_1_1_widget_and_chart_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['wimapdata',['WIMapData',['../class_templates_generator_tool_1_1_generators_1_1_generate_w_i_from_source_1_1_w_i_map_data.html',1,'TemplatesGeneratorTool.Generators.GenerateWIFromSource.WIMapData'],['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_w_i_map_data.html',1,'VstsRestAPI.WorkItemAndTracking.WIMapData']]],
  ['wiql',['Wiql',['../class_templates_generator_tool_1_1_view_model_1_1_query_response_1_1_wiql.html',1,'TemplatesGeneratorTool::ViewModel::QueryResponse']]],
  ['workitem',['Workitem',['../class_templates_generator_tool_1_1_view_model_1_1_get_work_items_response_1_1_workitem.html',1,'TemplatesGeneratorTool.ViewModel.GetWorkItemsResponse.Workitem'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_work_item.html',1,'VstsRestAPI.Viewmodel.WorkItem.WorkItemPatchResponse.WorkItem'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_get_work_items_response_1_1_workitem.html',1,'VstsRestAPI.Viewmodel.WorkItem.GetWorkItemsResponse.Workitem']]],
  ['workitembatchpostresponse',['WorkItemBatchPostResponse',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_batch_post_response.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['workitemfetchresponse',['WorkItemFetchResponse',['../class_templates_generator_tool_1_1_view_model_1_1_work_item_fetch_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['workitemhistory',['Workitemhistory',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_workitemhistory.html',1,'VstsRestAPI::Viewmodel::WorkItem::WorkItemPatchResponse']]],
  ['workitemnew',['WorkItemNew',['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_work_item_new.html',1,'VstsRestAPI::WorkItemAndTracking']]],
  ['workitempatch',['WorkItemPatch',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['workitempatchresponse',['WorkItemPatchResponse',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['workitemrevisions',['Workitemrevisions',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_workitemrevisions.html',1,'VstsRestAPI::Viewmodel::WorkItem::WorkItemPatchResponse']]],
  ['workitems',['WorkItems',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_import_work_item_model_1_1_work_items.html',1,'VstsRestAPI.Viewmodel.WorkItem.ImportWorkItemModel.WorkItems'],['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_work_items.html',1,'VstsRestAPI.WorkItemAndTracking.WorkItems'],['../class_templates_generator_tool_1_1_view_model_1_1_work_item_fetch_response_1_1_work_items.html',1,'TemplatesGeneratorTool.ViewModel.WorkItemFetchResponse.WorkItems']]],
  ['workitemtype',['Workitemtype',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_workitemtype.html',1,'VstsRestAPI::Viewmodel::WorkItem::WorkItemPatchResponse']]],
  ['workitemupdates',['Workitemupdates',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_workitemupdates.html',1,'VstsRestAPI::Viewmodel::WorkItem::WorkItemPatchResponse']]]
];
