var searchData=
[
  ['self',['Self',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_project_and_teams_1_1_account_members_1_1_self.html',1,'VstsRestAPI.Viewmodel.ProjectAndTeams.AccountMembers.Self'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_get_node_response_1_1_self.html',1,'VstsRestAPI.Viewmodel.WorkItem.GetNodeResponse.Self'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_get_nodes_response_1_1_self.html',1,'VstsRestAPI.Viewmodel.WorkItem.GetNodesResponse.Self'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_work_item_patch_response_1_1_self.html',1,'VstsRestAPI.Viewmodel.WorkItem.WorkItemPatchResponse.Self']]],
  ['sendemail',['SendEmail',['../class_vsts_demo_builder_1_1_controllers_1_1_environment_controller.html#a69d4ebc71322d09e96bab8cd604ebb46',1,'VstsDemoBuilder::Controllers::EnvironmentController']]],
  ['service',['Service',['../class_templates_generator_tool_1_1_view_model_1_1_service_end_points_response_1_1_service.html',1,'TemplatesGeneratorTool::ViewModel::ServiceEndPointsResponse']]],
  ['serviceendpoint',['ServiceEndPoint',['../class_vsts_rest_a_p_i_1_1_service_1_1_service_end_point.html',1,'VstsRestAPI::Service']]],
  ['serviceendpointmodel',['ServiceEndpointModel',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_service_1_1_service_endpoint_model.html',1,'VstsRestAPI::Viewmodel::Service']]],
  ['serviceendpointsresponse',['ServiceEndPointsResponse',['../class_templates_generator_tool_1_1_view_model_1_1_service_end_points_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['setareaforteams',['SetAreaForTeams',['../class_vsts_rest_a_p_i_1_1_projects_and_teams_1_1_team.html#ab7ec4e48d49881e50a0a7aae20ede38a',1,'VstsRestAPI::ProjectsAndTeams::Team']]],
  ['setbacklogiterationforteam',['SetBackLogIterationForTeam',['../class_vsts_rest_a_p_i_1_1_projects_and_teams_1_1_team.html#a9edc630def2d89f784812cf88f706a4c',1,'VstsRestAPI::ProjectsAndTeams::Team']]],
  ['setepicsettings',['SetEpicSettings',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_set_epic_settings.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['setiterationsforteam',['SetIterationsForTeam',['../class_vsts_rest_a_p_i_1_1_projects_and_teams_1_1_team.html#a513442a4bc421f2b3f0fb980d1c6ed72',1,'VstsRestAPI::ProjectsAndTeams::Team']]],
  ['settings',['Settings',['../class_templates_generator_tool_1_1_view_model_1_1_card_style_response_1_1_settings.html',1,'TemplatesGeneratorTool::ViewModel::CardStyleResponse']]],
  ['settingsversion',['SettingsVersion',['../class_templates_generator_tool_1_1_view_model_1_1_widget_and_chart_response_1_1_settings_version.html',1,'TemplatesGeneratorTool::ViewModel::WidgetAndChartResponse']]],
  ['signout',['SignOut',['../class_vsts_demo_builder_1_1_controllers_1_1_account_controller.html#abbf468c027b199a26ccc4a12fdad7fbe',1,'VstsDemoBuilder::Controllers::AccountController']]],
  ['size',['Size',['../class_templates_generator_tool_1_1_view_model_1_1_widget_and_chart_response_1_1_size.html',1,'TemplatesGeneratorTool::ViewModel::WidgetAndChartResponse']]],
  ['sourcecode',['SourceCode',['../class_templates_generator_tool_1_1_generators_1_1_source_code.html',1,'TemplatesGeneratorTool::Generators']]],
  ['sourcecoderesponse',['SourceCodeResponse',['../class_templates_generator_tool_1_1_view_model_1_1_source_code_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['sourceconfiguration',['SourceConfiguration',['../class_templates_generator_tool_1_1_source_configuration.html',1,'TemplatesGeneratorTool']]],
  ['startenvironmentsetupprocess',['StartEnvironmentSetupProcess',['../class_vsts_demo_builder_1_1_controllers_1_1_environment_controller.html#ad6b69ff448fc483cb517729d55c55dcc',1,'VstsDemoBuilder::Controllers::EnvironmentController']]],
  ['statemappings',['StateMappings',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_get_board_column_response_1_1_state_mappings.html',1,'VstsRestAPI.Viewmodel.WorkItem.GetBoardColumnResponse.StateMappings'],['../class_templates_generator_tool_1_1_view_model_1_1_board_columns_response_1_1_state_mappings.html',1,'TemplatesGeneratorTool.ViewModel.BoardColumnsResponse.StateMappings'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_state_mappings.html',1,'VstsRestAPI.Viewmodel.WorkItem.StateMappings']]],
  ['swimlanes',['SwimLanes',['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_swim_lanes.html',1,'VstsRestAPI::WorkItemAndTracking']]],
  ['systemdebug',['SystemDebug',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_system_debug.html',1,'TemplatesGeneratorTool::ViewModel::BuildDefinitions']]]
];
