var searchData=
[
  ['backlogiteration',['BacklogIteration',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_project_and_teams_1_1_team_setting_response_1_1_backlog_iteration.html',1,'VstsRestAPI::Viewmodel::ProjectAndTeams::TeamSettingResponse']]],
  ['backlogvisibilities',['BacklogVisibilities',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_set_epic_settings_1_1_backlog_visibilities.html',1,'VstsRestAPI::Viewmodel::WorkItem::SetEpicSettings']]],
  ['baseviewmodel',['BaseViewModel',['../class_templates_generator_tool_1_1_view_model_1_1_base_view_model.html',1,'TemplatesGeneratorTool.ViewModel.BaseViewModel'],['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_base_view_model.html',1,'VstsRestAPI.Viewmodel.BaseViewModel']]],
  ['batchrequest',['BatchRequest',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_work_item_1_1_batch_request.html',1,'VstsRestAPI::Viewmodel::WorkItem']]],
  ['boardcolumn',['BoardColumn',['../class_vsts_rest_a_p_i_1_1_work_item_and_tracking_1_1_board_column.html',1,'VstsRestAPI::WorkItemAndTracking']]],
  ['boardcolumns',['BoardColumns',['../class_templates_generator_tool_1_1_generators_1_1_board_columns.html',1,'TemplatesGeneratorTool::Generators']]],
  ['boardcolumnsresponse',['BoardColumnsResponse',['../class_templates_generator_tool_1_1_view_model_1_1_board_columns_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['bug',['Bug',['../class_templates_generator_tool_1_1_view_model_1_1_card_field_response_1_1_bug.html',1,'TemplatesGeneratorTool::ViewModel::CardFieldResponse']]],
  ['build',['Build',['../class_templates_generator_tool_1_1_view_model_1_1_build_definition_response_1_1_build.html',1,'TemplatesGeneratorTool.ViewModel.BuildDefinitionResponse.Build'],['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_build.html',1,'TemplatesGeneratorTool.ViewModel.BuildDefinitions.Build']]],
  ['buildconfiguration',['BuildConfiguration',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_build_configuration.html',1,'TemplatesGeneratorTool::ViewModel::BuildDefinitions']]],
  ['builddef',['BuildDef',['../class_vsts_demo_builder_1_1_models_1_1_build_def.html',1,'VstsDemoBuilder::Models']]],
  ['builddefinition',['BuildDefinition',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_build_definition.html',1,'TemplatesGeneratorTool.ViewModel.BuildDefinitions.BuildDefinition'],['../class_vsts_rest_a_p_i_1_1_build_1_1_build_definition.html',1,'VstsRestAPI.Build.BuildDefinition']]],
  ['builddefinitionresponse',['BuildDefinitionResponse',['../class_templates_generator_tool_1_1_view_model_1_1_build_definition_response.html',1,'TemplatesGeneratorTool::ViewModel']]],
  ['builddefinitions',['BuildDefinitions',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions.html',1,'TemplatesGeneratorTool.ViewModel.BuildDefinitions'],['../class_templates_generator_tool_1_1_generators_1_1_build_definitions.html',1,'TemplatesGeneratorTool.Generators.BuildDefinitions']]],
  ['buildgetlistofbuilddefinitionsresponse',['BuildGetListofBuildDefinitionsResponse',['../class_vsts_rest_a_p_i_1_1_viewmodel_1_1_build_1_1_build_get_listof_build_definitions_response.html',1,'VstsRestAPI::Viewmodel::Build']]],
  ['buildplatform',['BuildPlatform',['../class_templates_generator_tool_1_1_view_model_1_1_build_definitions_1_1_build_platform.html',1,'TemplatesGeneratorTool::ViewModel::BuildDefinitions']]],
  ['buildreleasemapping',['BuildReleaseMapping',['../class_vsts_demo_builder_1_1_models_1_1_build_release_mapping.html',1,'VstsDemoBuilder::Models']]],
  ['bundleconfig',['BundleConfig',['../class_vsts_demo_builder_1_1_bundle_config.html',1,'VstsDemoBuilder']]]
];
